<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Recontent.aspx.cs" 
                Inherits="VertoTestProject.Recontent" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:ValidationSummary ShowModelStateErrors="true" runat="server" />
    <h1>Small content manager</h1>
    <h2>Manage page contents</h2>
        <asp:GridView runat="server" ID="contentsGrid"
        ItemType="VertoTestProject.Models.Content" DataKeyNames="ContentID" 
        SelectMethod="contentsGrid_GetData"
        UpdateMethod="contentsGrid_UpdateItem" DeleteMethod="contentsGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"  
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="ContentID" />
            <asp:DynamicField DataField="TitleName" />   
            <asp:DynamicField DataField="ContentCon" /> 
        </Columns>
    </asp:GridView>

    <h2>Manage News</h2>
        <asp:GridView runat="server" ID="newsGrid"
        ItemType="VertoTestProject.Models.New" DataKeyNames="NewID" 
        SelectMethod="newsGrid_GetData"
        UpdateMethod="newsGrid_UpdateItem" DeleteMethod="newsGrid_DeleteItem"
        AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"  
        AutoGenerateColumns="false">
        <Columns>
            <asp:DynamicField DataField="NewID" />
            <asp:DynamicField DataField="NewName" />   
            <asp:DynamicField DataField="NewCon" /> 
        </Columns>
    </asp:GridView>
</asp:Content>